CMakeLists.txt: respect ${CMAKE_INSTALL_LIBDIR}
:Release Notes:
With multilib enabled the libdir is usr/lib64 or usr/lib32 instead
of usr/lib.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/793296

ERROR: QA Issue: lib32-media-codec-interface: Files/directories were
installed but not shipped in any package:
  /usr/lib/libmedia-codec-impl.so.1
  /usr/lib/libmedia-codec-interface.so
  /usr/lib/libmedia-codec-interface.so.1
  /usr/lib/libmedia-codec-impl.so
  /usr/lib/libmedia-codec-interface.so.1.0
  /usr/lib/libmedia-codec-impl.so.1.0
Please set FILES such that these items are packaged. Alternatively if
they are unneeded,avoid installing or deleteting them within do_install
lib32-media-codec-interface: 6 installed and not shipped files.
[installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-10922] Fix compilation errors in MCIL

Change-Id: I83b65b01b0b04c7e2b29f8977a4e2805165cb7bf
Reviewed-on: http://gpro.lge.com/c/webosose/media-codec-interface/+/396335
Reviewed-by: Sujeet Nayak <sujeet.nayak@lge.com>
Tested-by: Sujeet Nayak <sujeet.nayak@lge.com>
Tested-by: <vaibhav29.jadhav@lge.com>