fixup! Video Encoder/Decoder API changes for future expansion
:Release Notes:
Fix compilaton error in GstVideoEncoder after Initialize API change

:Detailed Notes:
Fix below compilaton error in GstVideoEncoder after Initialize API
changed in previous commit.

gst_video_encoder.h:33:8: error: 'bool mcil::GstVideoEncoder::Initialize(const mcil::EncoderConfig*, mcil::VideoEncoderClient*, int, bool*, bool*, size_t*)' marked 'override', but does not override
|    33 |   bool Initialize(const EncoderConfig* configData,
|       |        ^~~~~~~~~~

Also change return type of init input/output memory functions

:Testing Performed:
Build on RPi4 target success.
Also tested glitch me test site is working fine with GST encoder

:QA Notes:
NA

:Issues Addressed:
NA

Change-Id: I31d6bab92172d2d9906f22123416a15b47b9fb9d
Reviewed-on: http://gpro.lge.com/c/webosose/media-codec-interface/+/330957
Tested-by: Pankaj Maharana <pankaj.maharana@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Rajesh Nagaiya <rajesh.n@lge.com>
Reviewed-by: Pankaj Maharana <pankaj.maharana@lge.com>