fixup! Rename codec_api as api and add impl from media-codec-ose
:Release Notes:
Fixup compilation error due to missing changes from the renaming
codec api commit patch

:Detailed Notes:
Fix below compilation error due to missing changes in api/CMakeList.txt
file

| CMake Error at src/api/CMakeLists.txt:42 (add_library):
|   Cannot find source file:
|
|     codec_api/video_decoder_api.cpp

:Testing Performed:
Build only on both Rpi and GE target.
Also tested MSE/URL video playbacks in Rpi4 and Qti platform builds

:QA Notes:
NA

:Issues Addressed:
NA

Change-Id: I111c8f3629f570b7464d075067d2d7dc11b30f11
Reviewed-on: http://gpro.lge.com/c/webosose/media-codec-interface/+/330722
Tested-by: Pankaj Maharana <pankaj.maharana@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Pankaj Maharana <pankaj.maharana@lge.com>